trigger:
  branches:
    include:
      - master
      - staging

pool:
  name: autohospedado

steps:
  - task: MavenAuthenticate@0
    inputs:
      mavenAuthenticate: true
  
  - task: Maven@3
    inputs:
      mavenPomFile: 'pom.xml'
      goals: 'clean install'
      publishJUnitResults: true
      testResultsFiles: '**/TEST-*.xml'

  - task: AzureWebApp@1
    inputs:
      azureSubscription: 'monitor'
      appName: 'Ambiental-monitor'
      package: '$(System.DefaultWorkingDirectory)/**/*.jar'
      deploymentMethod: 'auto'
