trigger:
  branches:
    include:
      - master
      - staging

pool:
  name: autohospedado  # Substitua pelo nome do seu pool de agentes se necessário

variables:
  appName: "monitoramentoambiental"
  artifactName: "monitoramento_ambiental-0.0.1-SNAPSHOT.jar"
  resourceGroup: "Trabalhos"

jobs:
- job: build
  displayName: 'Build Job'
  pool:
    name: autohospedado  # ou o nome do seu agente auto-hospedado
  steps:
    - script: echo %PATH%
      displayName: 'Check PATH Variable'

    - script: mvn -v
      displayName: 'Check Maven Version'
      
    - task: MavenAuthenticate@0
      inputs:
        mavenAuthenticate: true

    - script: mvn clean install
      displayName: 'Build with Maven'
      workingDirectory: '$(Build.SourcesDirectory)'

    - script: mvn test
      displayName: 'Run Tests'
      workingDirectory: '$(Build.SourcesDirectory)'

    - task: PublishBuildArtifacts@1
      inputs:
        PathtoPublish: 'target/$(artifactName)'
        ArtifactName: 'app-package'

- job: deploy_staging
  displayName: 'Deploy to Staging'
  dependsOn: build
  condition: eq(variables['Build.SourceBranch'], 'refs/heads/staging')
  pool:
    name: autohospedado  # ou o nome do seu agente auto-hospedado
  steps:
    - task: DownloadBuildArtifacts@1
      inputs:
        buildType: 'current'
        downloadPath: '$(System.DefaultWorkingDirectory)'

    - task: AzureCLI@2
      inputs:
        azureSubscription: 'monitor'  # Altere para o nome do seu serviço de conexão Azure
        scriptType: 'ps'
        scriptLocation: 'inlineScript'
        inlineScript: |
          $resourceGroup = "$(resourceGroup)"
          $appName = "$(appName)"
          $slotName = "staging"
          $srcPath = "$(System.DefaultWorkingDirectory)/app-package/$(artifactName)"

          # Verificar se o caminho do arquivo de origem existe
          if (Test-Path $srcPath) {
              az webapp deploy --resource-group $resourceGroup --name $appName --slot $slotName --src-path $srcPath
          } else {
              Write-Host "O caminho de origem não existe: $srcPath"
              exit 1  # Saia com código de erro se o arquivo não for encontrado
          }

- job: deploy_production
  displayName: 'Swap Staging to Production'
  dependsOn: deploy_staging
  condition: eq(variables['Build.SourceBranch'], 'refs/heads/staging')
  pool:
    name: autohospedado  # ou o nome do seu agente auto-hospedado
  steps:
    - task: AzureCLI@2
      inputs:
        azureSubscription: 'monitor'  # Altere para o nome do seu serviço de conexão Azure
        scriptType: 'bash'
        scriptLocation: 'inlineScript'
        inlineScript: |
          az webapp deployment slot swap --resource-group $(resourceGroup) --name $(appName) --slot staging --target-slot production
